name: reactive_counter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # Additional reactive add-ons for dart streams.
  rxdart: "^0.18.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true